### ISSUE TITLE
Fail to compile on Ubuntu 13.10

### ISSUE THREAD

**Issue by CristianCantoro** [nneonneo/2048-ai#3]
I am  running Ubuntu 13.10, here's what I get:

``` bash
~/2048-ai$ make
g++  -O3 -Wall -Werror -Wextra -std=c++11  -c -o bin/2048.o 2048.cpp
2048.cpp: In function ‘int find_best_move(board_t)’:
2048.cpp:348:41: error: taking address of temporary array
     printf("%s\n", BOARDSTR(board, '\n'));
                                         ^
2048.cpp: In function ‘int ask_for_move(board_t)’:
2048.cpp:368:41: error: taking address of temporary array
     printf("%s\n", BOARDSTR(board, '\n'));
                                         ^
In file included from 2048.cpp:10:0:
2048.cpp: In function ‘int draw_tile()’:
2048.h:5:44: error: ‘arc4random_uniform’ was not declared in this scope
 #define UNIF_RANDOM(n) arc4random_uniform(n)
                                            ^
2048.cpp:398:13: note: in expansion of macro ‘UNIF_RANDOM’
     return (UNIF_RANDOM(10) < 9) ? 1 : 2;
             ^
2048.cpp: In function ‘board_t insert_tile_rand(board_t, int)’:
2048.h:5:44: error: ‘arc4random_uniform’ was not declared in this scope
 #define UNIF_RANDOM(n) arc4random_uniform(n)
                                            ^
2048.cpp:413:17: note: in expansion of macro ‘UNIF_RANDOM’
     int index = UNIF_RANDOM(num_open);
                 ^
2048.cpp: In function ‘void play_game(get_move_func_t)’:
2048.cpp:474:41: error: taking address of temporary array
     printf("%s\n", BOARDSTR(board, '\n'));
                                         ^
2048.cpp: In function ‘int draw_tile()’:
2048.cpp:399:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make: *** [bin/2048.o] Error 1
cristian@FBK-41512:~/2048-ai$ g++
g++: fatal error: no input files
compilation terminated.
```

My `g++` version is:

``` bash
~/2048-ai$ g++ --version
g++ (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
